Matts post picker modifications
humanmade/block-editor-components pull request #142
Opened 2023-06-01 16:30 UTC by mattheu

I've been reviewing this PR and getting it to work on my project. This is what I've changed: 

* Renamed `.jsx` to `.js` so that it actually builds. 
* Fix typo in index.js
* Support for multiple taxonomies. I ran into some issues with taxonomies like post tag where the taxonomy slug `post_tag` is different from the `rest_base` (`tags`) and the singular name (`Tag`). 
* Move the actual `getEntityRecords` call into `PostList`, so that the query is done only when opening the modal, and not on initial page load. 
* Reduce the number of queried posts to `30` instead of `-1`. Unbounded queries are not very fast... I've got some unrelated performance issues it seems on my local dev site... but this was taking way too long. Long term... would love pagination but as an MVP, being able to search/filter you probably don't need to list everything.

2023-06-02 09:45 UTC, tomjn commented on src/components/PostPicker/index.js
> +								label={ post.title?.rendered || __( '(No title)', 'block-editor-components' ) }
Things are nicer with spaces

```suggestion
								label={ post.title?.rendered || __( '( No title )', 'block-editor-components' ) }
```

2023-06-02 09:47 UTC, tomjn requested changes
2 changes but otherwise a good improvement to the PR

2023-06-02 09:47 UTC, tomjn commented on src/components/TermSelector/index.js
> +		label={ `Filter by ${ taxObject ? taxObject.labels.singular_name : '' }` }
should this be translatable?

2023-06-02 09:51 UTC, mattheu commented on src/components/TermSelector/index.js
> +		label={ `Filter by ${ taxObject ? taxObject.labels.singular_name : '' }` }
Good catch. Fixed.

2023-06-02 16:13 UTC, tomjn approved these changes
👍🏻 good changes

2023-06-05 12:40 UTC, mattheu commented
As @tomjn approved this, going to merge into Joe's feature branch.

2023-06-05 12:40 UTC, merged